author: ridedott
branding:
  color: gray-dark
  icon: package
description: A GitHub Action for Semantic Release.
inputs:
  gpr-token:
    description: GitHub token with access to publish to the GitHub Package Registry.
    required: false
  npm-token:
    description: NPM token with access to publish to the NPM Registry.
    required: false
  dry-run:
    default: 'false'
    description: 'Skips `prepare`, `publish` and `success` steps.'
    required: false
name: Publish me!
runs:
  main: dist/index.js
  using: node12
