author: ridedott
branding:
  color: gray-dark
  icon: package
description: A GitHub Action for Semantic Release.
inputs:
  branch:
    default: master
    description: A git branch to release from.
    required: false
  debug:
    default: 'false'
    description: Outputs debug information for semantic-release plugins.
    required: false
  dry-run:
    default: 'false'
    description: 'Skips `prepare`, `publish` and `success` steps.'
    required: false
name: Publish me!
runs:
  args:
    - ${{ inputs.branch }}
    - ${{ inputs.debug }}
    - ${{ inputs.dry-run }}
  image: Dockerfile
  using: docker
