name: Continuous Delivery

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Fetch all history.
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v1
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          key:
            npm-${{ hashFiles(format('{0}{1}', github.workspace,
            '/package-lock.json')) }}
          path: ~/.npm
          restore-keys: |
            npm-
      - name: Install dependencies
        run: npm ci --ignore-scripts --no-audit --no-progress --prefer-offline
      - name: Build
        run: |
          # Workaround https://github.com/zeit/ncc/issues/457.
          mv tsconfig.production.json tsconfig.json
          npm run build
      - name: Release
        uses: ridedott/semantic-release-action@master
        env:
          # This must be used as GitHub Actions token does not support pushing
          # to protected branches.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_DOTTBOTT }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN_DOTTBOTT }}
        with:
          BRANCH: master
