name: Continuous Integration

on: push

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run format
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - env:
          CI: true
        run: npm ci
      - run: npm run lint
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - env:
          CI: true
        run: npm ci
      - run: npm run spellcheck
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - env:
          CI: true
        run: npm ci
      - run: npm test
  types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - env:
          CI: true
        run: npm ci
      - run: npm run types
  semantic-release-publish:
    name: Publish new version with Semantic-release action
    runs-on: ubuntu-latest
    needs:
      - format
      - lint
      - spellcheck
      - test
      - types
    steps:
      - name: semantic-release-publish
        uses: ridedott/semantic-release-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRY_RUN: true
          DEBUG: true
